apiVersion: v1
kind: Service
metadata:
  name: tienda-online
  labels:
    app: tienda-online
spec:
  type: NodePort
  selector:
    app: tienda-online
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30900
    protocol: TCP
